language: python
python:
  - ""3.6""

#Install dependecies
install:
  - pip install -r requirements.txt
  - psql -c 'create database swett;' -U postgres

#Run tests
script:
  - pytest --cov

after_success:
  - coveralls

notifications:
  email: false